import type { Transaction } from '@/entities/transaction/model/types'

export const mockTransactions: Transaction[] = [
  {
    id: 'trx-1',
    date: '2026-02-22',
    description: 'Супермаркет',
    category: 'Продукты',
    account: 'Основная карта',
    amount: -84.2,
    currency: 'USD',
    kind: 'EXPENSE',
    status: 'Completed',
  },
  {
    id: 'trx-2',
    date: '2026-02-21',
    description: 'Зарплата',
    category: 'Основной доход',
    account: 'Накопительный счет',
    amount: 2900,
    currency: 'USD',
    kind: 'INCOME',
    status: 'Completed',
  },
  {
    id: 'trx-3',
    date: '2026-02-20',
    description: 'Кофейня',
    category: 'Кафе',
    account: 'Основная карта',
    amount: -11.5,
    currency: 'USD',
    kind: 'EXPENSE',
    status: 'Completed',
  },
  {
    id: 'trx-4',
    date: '2026-02-19',
    description: 'Фриланс',
    category: 'Доп. доход',
    account: 'Основная карта',
    amount: 620,
    currency: 'USD',
    kind: 'INCOME',
    status: 'Pending',
  },
  {
    id: 'trx-5',
    date: '2026-02-18',
    description: 'Подписка SaaS',
    category: 'Сервисы',
    account: 'Основная карта',
    amount: -19,
    currency: 'USD',
    kind: 'EXPENSE',
    status: 'Completed',
  },
  {
    id: 'trx-6',
    date: '2026-02-16',
    description: 'Пополнение наличных',
    category: 'Перевод',
    account: 'Наличные',
    amount: 200,
    currency: 'USD',
    kind: 'TRANSFER',
    status: 'Completed',
  },
]

export const mockTransfers: Transaction[] = mockTransactions.filter(
  (item) => item.kind === 'TRANSFER',
)
